[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.3",
    "plotly>=5.24.1",
    "scipy>=1.14.1",
    "streamlit>=1.40.0",
    "torch>=2.5.1",
]
